aux_penalty: 0.03125
bandwidth: 0.001
batch_size: 128
beta1: 0.9
beta2: 0.99
checkpoint_freq: 5000
checkpoint_path: null
config_save_path: ./configs/
dataset: monology/pile-uncopyrighted
device: cuda
dictionary_factor: 16
input_unit_norm: true
k: 76
l1_coeff: 0.004
layer: 8
log_path: ./logs/
lr: 0.0003
max_grad_norm: 100000
model_name: openai-community/gpt2
n_batches_to_dead: 5
num_batches_in_buffer: 10
num_tokens: 1000000000
perf_log_freq: 1000
sae_name: jumprelu
seed: 42
seq_len: 128
steps: 10000
top_k_aux: 512
torch_dtype: bfloat16
training_steps: 30000
verbose: true
